In [2]:
import pandas as pd

In [6]:
df = pd.read_csv('dataset_ecommerce.csv', encoding='windows-1252')

In [18]:
df.head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/2010 8:26,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/1/2010 8:26,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,12/1/2010 8:34,1.69,13047.0,United Kingdom
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,12/1/2010 8:34,2.10,13047.0,United Kingdom
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,12/1/2010 8:34,2.10,13047.0,United Kingdom
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,12/1/2010 8:34,3.75,13047.0,United Kingdom
13,536367,22310,IVORY KNITTED MUG COSY,6,12/1/2010 8:34,1.65,13047.0,United Kingdom
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,12/1/2010 8:34,4.25,13047.0,United Kingdom
15,536367,22623,BOX OF VINTAGE JIGSAW BLOCKS,3,12/1/2010 8:34,4.95,13047.0,United Kingdom
16,536367,22622,BOX OF VINTAGE ALPHABET BLOCKS,2,12/1/2010 8:34,9.95,13047.0,United Kingdom
17,536367,21754,HOME BUILDING BLOCK WORD,3,12/1/2010 8:34,5.95,13047.0,United Kingdom
18,536367,21755,LOVE BUILDING BLOCK WORD,3,12/1/2010 8:34,5.95,13047.0,United Kingdom
19,536367,21777,RECIPE BOX WITH METAL HEART,4,12/1/2010 8:34,7.95,13047.0,United Kingdom

In [21]:
# Listando as colunas
print(df.columns)

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [23]:
# Criando um novo DataFrame 'dfCustomer' com CustomerID não nulo
dfCustomer = df[df['CustomerID'].notna()].copy()

In [25]:
def classificar_invoice(invoice_no):
    """Classifica o InvoiceNo com base no primeiro caractere."""
    if isinstance(invoice_no, str) and invoice_no:  # Verifica se é string e não está vazio
        if invoice_no.startswith('A'):
            return 'Ajustar'
        elif invoice_no.startswith('C'):
            return 'Cancelada'
        else:
            return 'Registrada'
    else:
        return 'Registrada' # Caso não seja string ou esteja vazio, retorna 'Registrada'


# Aplica a função para criar a nova coluna 'StatusInvoice'
dfCustomer['StatusInvoice'] = dfCustomer['InvoiceNo'].apply(classificar_invoice)

# Exibe o DataFrame com a nova coluna
print(dfCustomer[['InvoiceNo', 'StatusInvoice']]) #exibe apenas as colunas relevantes para verificar o resultado.

       InvoiceNo StatusInvoice
0         536365    Registrada
1         536365    Registrada
2         536365    Registrada
3         536365    Registrada
4         536365    Registrada
...          ...           ...
541904    581587    Registrada
541905    581587    Registrada
541906    581587    Registrada
541907    581587    Registrada
541908    581587    Registrada

[406829 rows x 2 columns]

In [27]:
dfCustomer.head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,StatusInvoice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom,Registrada
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,Registrada
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom,Registrada
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,Registrada
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,Registrada
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/2010 8:26,7.65,17850.0,United Kingdom,Registrada
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/1/2010 8:26,4.25,17850.0,United Kingdom,Registrada
7,536366,22633,HAND WARMER UNION JACK,6,12/1/2010 8:28,1.85,17850.0,United Kingdom,Registrada
8,536366,22632,HAND WARMER RED POLKA DOT,6,12/1/2010 8:28,1.85,17850.0,United Kingdom,Registrada
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,12/1/2010 8:34,1.69,13047.0,United Kingdom,Registrada
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,12/1/2010 8:34,2.10,13047.0,United Kingdom,Registrada
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,12/1/2010 8:34,2.10,13047.0,United Kingdom,Registrada
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,12/1/2010 8:34,3.75,13047.0,United Kingdom,Registrada
13,536367,22310,IVORY KNITTED MUG COSY,6,12/1/2010 8:34,1.65,13047.0,United Kingdom,Registrada
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,12/1/2010 8:34,4.25,13047.0,United Kingdom,Registrada
15,536367,22623,BOX OF VINTAGE JIGSAW BLOCKS,3,12/1/2010 8:34,4.95,13047.0,United Kingdom,Registrada
16,536367,22622,BOX OF VINTAGE ALPHABET BLOCKS,2,12/1/2010 8:34,9.95,13047.0,United Kingdom,Registrada
17,536367,21754,HOME BUILDING BLOCK WORD,3,12/1/2010 8:34,5.95,13047.0,United Kingdom,Registrada
18,536367,21755,LOVE BUILDING BLOCK WORD,3,12/1/2010 8:34,5.95,13047.0,United Kingdom,Registrada
19,536367,21777,RECIPE BOX WITH METAL HEART,4,12/1/2010 8:34,7.95,13047.0,United Kingdom,Registrada

In [29]:
contagem_status = dfCustomer['StatusInvoice'].value_counts()

print(contagem_status)

StatusInvoice
Registrada    397924
Cancelada       8905
Name: count, dtype: int64

In [31]:
import re

def extrair_numeros(invoice_no):
    """Extrai os números de uma string InvoiceNo."""
    if isinstance(invoice_no, str):
        numeros = re.findall(r'\d+', invoice_no) # Encontra todas as sequências de dígitos
        if numeros:
            return ''.join(numeros) # Junta os números encontrados em uma única string
        else:
            return None # Retorna None se nenhum número for encontrado
    else:
        return None # Retorna None se o valor não for uma string

# Aplica a função para criar a nova coluna 'InvoiceNumber'
dfCustomer['InvoiceNumber'] = dfCustomer['InvoiceNo'].apply(extrair_numeros)

# Exibe o DataFrame com a nova coluna
print(dfCustomer[['InvoiceNo', 'InvoiceNumber']].head()) # Exibe as primeiras linhas para verificação

  InvoiceNo InvoiceNumber
0    536365        536365
1    536365        536365
2    536365        536365
3    536365        536365
4    536365        536365

In [35]:
print(dfCustomer[dfCustomer['StatusInvoice'] == 'Cancelada'].head(20))

     InvoiceNo StockCode                          Description  Quantity  \
141    C536379         D                             Discount        -1
154    C536383    35004C      SET OF 3 COLOURED  FLYING DUCKS        -1
235    C536391     22556       PLASTERS IN TIN CIRCUS PARADE        -12
236    C536391     21984     PACK OF 12 PINK PAISLEY TISSUES        -24
237    C536391     21983     PACK OF 12 BLUE PAISLEY TISSUES        -24
238    C536391     21980    PACK OF 12 RED RETROSPOT TISSUES        -24
239    C536391     21484          CHICK GREY HOT WATER BOTTLE       -12
240    C536391     22557     PLASTERS IN TIN VINTAGE PAISLEY        -12
241    C536391     22553               PLASTERS IN TIN SKULLS       -24
939    C536506     22960             JAM MAKING SET WITH JARS        -6
1441   C536543     22632            HAND WARMER RED RETROSPOT        -1
1442   C536543     22355            CHARLOTTE BAG SUKI DESIGN        -2
1973   C536548     22244           3 HOOK HANGER MAGIC GARDEN        -4
1974   C536548     22242        5 HOOK HANGER MAGIC TOADSTOOL        -5
1975   C536548     20914  SET/5 RED RETROSPOT LID GLASS BOWLS        -1
1976   C536548     22892    SET OF SALT AND PEPPER TOADSTOOLS        -7
1977   C536548     22654                   DELUXE SEWING KIT         -1
1978   C536548     22767          TRIPLE PHOTO FRAME CORNICE         -2
1979   C536548     22333    RETROSPOT PARTY BAG + STICKER SET        -1
1980   C536548     22245         HOOK, 1 HANGER ,MAGIC GARDEN        -2

          InvoiceDate  UnitPrice  CustomerID         Country StatusInvoice  \
141    12/1/2010 9:41      27.50     14527.0  United Kingdom     Cancelada
154    12/1/2010 9:49       4.65     15311.0  United Kingdom     Cancelada
235   12/1/2010 10:24       1.65     17548.0  United Kingdom     Cancelada
236   12/1/2010 10:24       0.29     17548.0  United Kingdom     Cancelada
237   12/1/2010 10:24       0.29     17548.0  United Kingdom     Cancelada
238   12/1/2010 10:24       0.29     17548.0  United Kingdom     Cancelada
239   12/1/2010 10:24       3.45     17548.0  United Kingdom     Cancelada
240   12/1/2010 10:24       1.65     17548.0  United Kingdom     Cancelada
241   12/1/2010 10:24       1.65     17548.0  United Kingdom     Cancelada
939   12/1/2010 12:38       4.25     17897.0  United Kingdom     Cancelada
1441  12/1/2010 14:30       2.10     17841.0  United Kingdom     Cancelada
1442  12/1/2010 14:30       0.85     17841.0  United Kingdom     Cancelada
1973  12/1/2010 14:33       1.95     12472.0         Germany     Cancelada
1974  12/1/2010 14:33       1.65     12472.0         Germany     Cancelada
1975  12/1/2010 14:33       2.95     12472.0         Germany     Cancelada
1976  12/1/2010 14:33       1.25     12472.0         Germany     Cancelada
1977  12/1/2010 14:33       5.95     12472.0         Germany     Cancelada
1978  12/1/2010 14:33       9.95     12472.0         Germany     Cancelada
1979  12/1/2010 14:33       1.65     12472.0         Germany     Cancelada
1980  12/1/2010 14:33       0.85     12472.0         Germany     Cancelada

     InvoiceNumber
141         536379
154         536383
235         536391
236         536391
237         536391
238         536391
239         536391
240         536391
241         536391
939         536506
1441        536543
1442        536543
1973        536548
1974        536548
1975        536548
1976        536548
1977        536548
1978        536548
1979        536548
1980        536548