# <font color='green'>PROJETO INTEGRADOR 3 - Análise de Dados 1</font>
# <font color='green'>Projeto 5 - Diabetes dos Índios Pima - Parte 21</font>>
## <font color='green'>Começando a Limpeza dos Dados - A</font>

## Instalando e Carregando os Pacotes

In [3]:
# Importando os pacotes/blibliotecas
import math
import numpy as np
import pandas as pd

# Criamos uma lista para identificar valores ausentes
lista_labels_valores_ausentes = ["n/a", "na", "NA", "undefined"]

# Carregando o Dataset
dataset = pd.read_csv("diabetes.csv", na_values = lista_labels_valores_ausentes)

# Carregando o módulo que contém as funções específicas para limpeza de Dados
from limpeza_dados import *

In [9]:
pip install watermark

Requirement already satisfied: watermark in c:\users\miche\anaconda3\lib\site-packages (2.5.0)
Requirement already satisfied: ipython>=6.0 in c:\users\miche\anaconda3\lib\site-packages (from watermark) (8.15.0)
Requirement already satisfied: importlib-metadata>=1.4 in c:\users\miche\anaconda3\lib\site-packages (from watermark) (6.0.0)
Requirement already satisfied: setuptools in c:\users\miche\anaconda3\lib\site-packages (from watermark) (68.0.0)
Requirement already satisfied: zipp>=0.5 in c:\users\miche\anaconda3\lib\site-packages (from importlib-metadata>=1.4->watermark) (3.11.0)
Requirement already satisfied: backcall in c:\users\miche\anaconda3\lib\site-packages (from ipython>=6.0->watermark) (0.2.0)
Requirement already satisfied: decorator in c:\users\miche\anaconda3\lib\site-packages (from ipython>=6.0->watermark) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\miche\anaconda3\lib\site-packages (from ipython>=6.0->watermark) (0.18.1)
Requirement already satisfied: matplotlib-inline in c:\users\miche\anaconda3\lib\site-packages (from ipython>=6.0->watermark) (0.1.6)
Requirement already satisfied: pickleshare in c:\users\miche\anaconda3\lib\site-packages (from ipython>=6.0->watermark) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in c:\users\miche\anaconda3\lib\site-packages (from ipython>=6.0->watermark) (3.0.36)
Requirement already satisfied: pygments>=2.4.0 in c:\users\miche\anaconda3\lib\site-packages (from ipython>=6.0->watermark) (2.15.1)
Requirement already satisfied: stack-data in c:\users\miche\anaconda3\lib\site-packages (from ipython>=6.0->watermark) (0.2.0)
Requirement already satisfied: traitlets>=5 in c:\users\miche\anaconda3\lib\site-packages (from ipython>=6.0->watermark) (5.7.1)
Requirement already satisfied: colorama in c:\users\miche\anaconda3\lib\site-packages (from ipython>=6.0->watermark) (0.4.6)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\miche\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=6.0->watermark) (0.8.3)
Requirement already satisfied: wcwidth in c:\users\miche\anaconda3\lib\site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython>=6.0->watermark) (0.2.5)
Requirement already satisfied: executing in c:\users\miche\anaconda3\lib\site-packages (from stack-data->ipython>=6.0->watermark) (0.8.3)
Requirement already satisfied: asttokens in c:\users\miche\anaconda3\lib\site-packages (from stack-data->ipython>=6.0->watermark) (2.0.5)
Requirement already satisfied: pure-eval in c:\users\miche\anaconda3\lib\site-packages (from stack-data->ipython>=6.0->watermark) (0.2.2)
Requirement already satisfied: six in c:\users\miche\anaconda3\lib\site-packages (from asttokens->stack-data->ipython>=6.0->watermark) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [11]:
# Versões dos pacotes usados neste jupyter notebook
%reload_ext watermark
%watermark -a "pyPRO - Transformando Vidas com o Poder do Código!" --iversions

Author: pyPRO - Transformando Vidas com o Poder do Código!

json  : 2.0.9
pandas: 2.0.3
numpy : 1.24.3

### Limpando os Dados - A

In [14]:
dataset.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [16]:
# Shape
dataset.shape

(768, 9)

In [18]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [20]:
# Verificar os valores ausentes no dataset
dataset.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [22]:
# Verificando os valores ausentes no dataset com as funções:
# Porcentual total de valores ausentes
calcular_porcentagem_valores_ausentes(dataset)

O conjunto de dados tem 0.0% de valores ausentes.

In [24]:
# Porcentagem de valores ausentes por coluna
relatorio_valores_ausentes_por_coluna(dataset)

O conjunto de dados tem 9 colunas.
Foram encontradas 0 colunas com valores ausentes.

Empty DataFrame
Columns: [Quantidade de Ausentes, Porcentagem de Ausentes, Tipo de Dado]
Index: []

In [26]:
dataset.sample(30)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
730,3,130,78,23,79,28.4,0.323,34,1
240,1,91,64,24,0,29.2,0.192,21,0
687,1,107,50,19,0,28.3,0.181,29,0
704,4,110,76,20,100,28.4,0.118,27,0
418,1,83,68,0,0,18.2,0.624,27,0
177,0,129,110,46,130,67.1,0.319,26,1
496,5,110,68,0,0,26.0,0.292,30,0
670,6,165,68,26,168,33.6,0.631,49,0
23,9,119,80,35,0,29.0,0.263,29,1
162,0,114,80,34,285,44.2,0.167,27,0
2,8,183,64,0,0,23.3,0.672,32,1
546,5,187,76,27,207,43.6,1.034,53,1
605,1,124,60,32,0,35.8,0.514,21,0
270,10,101,86,37,0,45.6,1.136,38,1
259,11,155,76,28,150,33.3,1.353,51,1
565,2,95,54,14,88,26.1,0.748,22,0
291,0,107,62,30,74,36.6,0.757,25,1
703,2,129,0,0,0,38.5,0.304,41,0
136,0,100,70,26,50,30.8,0.597,21,0
88,15,136,70,32,110,37.1,0.153,43,1
325,1,157,72,21,168,25.6,0.123,24,0
688,1,140,74,26,180,24.1,0.828,23,0
478,8,126,74,38,75,25.9,0.162,39,0
310,6,80,66,30,0,26.2,0.313,41,0
702,1,168,88,29,0,35.0,0.905,52,1
692,2,121,70,32,95,39.1,0.886,23,0
75,1,0,48,20,0,24.7,0.140,22,0
395,2,127,58,24,275,27.7,1.600,25,0
274,13,106,70,0,0,34.2,0.251,52,0
574,1,143,86,30,330,30.1,0.892,23,0

In [30]:
# Verificando o total de valores iguais a zero por coluna
dataset.apply(lambda x: (x==0).sum())

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                     500
dtype: int64

Notamos que aqui não se trata de um dataset com valores nulos (ausência de dados). **Aqui é o caso de ausência de informação**. 

Esse é o tipo de limpeza de dados mais difícil a ser realizado, pois temos que ter a certeza que do que se trata: o "zero" é informação ou ausência de informação?

In [33]:
# Vamos alterar essa ausência de informação em ausência de dados!
# coluna GLUCOSE
dataset["Glucose"] = dataset["Glucose"].apply(lambda x: np.nan if x == 0 else x)
# coluna BLOODPRESSURE
dataset["BloodPressure"] = dataset["BloodPressure"].apply(lambda x: np.nan if x == 0 else x)
# coluna SKINTHICKNESS
dataset["SkinThickness"] = dataset["SkinThickness"].apply(lambda x: np.nan if x == 0 else x)
# coluna INSULIN
dataset["Insulin"] = dataset["Insulin"].apply(lambda x: np.nan if x == 0 else x)
# coluna BMI
dataset["BMI"] = dataset["BMI"].apply(lambda x: np.nan if x == 0 else x)

In [35]:
# Verificando os valores ausentes no dataset com as funções:
# Porcentual total de valores ausentes
calcular_porcentagem_valores_ausentes(dataset)

O conjunto de dados tem 9.43% de valores ausentes.

In [37]:
# Porcentagem de valores ausentes por coluna
relatorio_valores_ausentes_por_coluna(dataset)

O conjunto de dados tem 9 colunas.
Foram encontradas 5 colunas com valores ausentes.

               Quantidade de Ausentes  Porcentagem de Ausentes Tipo de Dado
Insulin                           374                    48.70      float64
SkinThickness                     227                    29.56      float64
BloodPressure                      35                     4.56      float64
BMI                                11                     1.43      float64
Glucose                             5                     0.65      float64

### Salvando os Dados desta Etapa.

In [40]:
# Salvando os dados
dataset.to_csv('dataset_parte2.csv')

## <font color='green'>Fim da Parte 02</font>